insert into discovery.channels (youtube_channel_id, title, kind, in_daily_subscriptions, priority, active) values
('UCuYN15i2J_gETGamUAjEIWA','RADIO RCJ','media',true,2,true),
('UCCCPCZNChQdGa9EkATeye4g','FRANCE 24','media',true,1,true),
('UCMPnD8fhwPMk_9XsYfc96JQ','France 3 Provence-Alpes-Côte d''Azur','media',true,2,true),
('UCHQda5vLxrH0Ff0I0kMq4zw','Konbini','media',true,2,true),
('UC3Sk_YpjPd_Lz_oPQfhPQXQ','M6 Info','media',true,2,true),
('UCd5DKToXYTKAQ6khzewww2g','France Culture','media',true,1,true),
('UCwVhIWn5uFYaUrurDS5tWEA','outremernews onews','media',true,2,true),
('UCar0yo-PpeMk51m116826pQ','Journal l''Humanité','media',true,2,true),
('UCb4UAZwZqS4a35FrBcLlMXA','CANAL+','media',true,2,true),
('UCdnaDhU-LDQrIEEmSIfq0-Q','Mediapart','media',true,2,true),
('UC_ykXc7v9zZQdOG5QvJqpgg','RTL','media',true,1,true),
('UCIQGSp79vVch0vO3Efqif_w','FRANÇOIS RUFFIN','person',true,1,true),
('UCzKH70qfN_yuXq3s91fdwmg','TV5MONDE Info','media',true,2,true),
('UCXz1rrA8Pp2-1LJSkQQhbxw','France-Antilles & France-Guyane','media',true,2,true),
('UC-LaL6VO2SpXpjPdQT668wg','Groupe Nice-Matin','media',true,2,true),
('UCJgNMdfAExlU7MwHlET6XCw','France 3 Paris Ile-de-France','media',true,2,true),
('UCu0C2YqRHjyG-5KwozeyLFA','ToneFrance','media',true,2,true),
('UCvg4_wSz4Cmo4xRPXaKU47A','C dans l''air - France Télévisions','media',true,1,true),
('UC6kvMQP9gzv6qwwzMLuwZTg','France 3 Grand Est','media',true,2,true),
('UC8EzKGkEiusTm7g0mTfkWkg','28 minutes - ARTE','media',true,2,true),
('UCwTvW0qRQXV-yvBghNVgqKg','France 3 Nouvelle-Aquitaine','media',true,2,true),
('UCAcAnMF0OrCtUep3Y4M-ZPw','HugoDécrypte - Actus du jour','media',true,2,true),
('UCQd5LYcykaFeZtjDaP3bNSA','Le Point','media',true,2,true),
('UCD25QI36ly-8hWm9OPOz7aw','20 Minutes France','media',true,2,true),
('UCCDz_XYeKWd0OIyjp95dqyQ','Le Figaro','media',true,1,true),
('UCk-_PEY3iC6DIGJKuoEe9bw','JEAN-LUC MÉLENCHON','person',true,1,true),
('UCpQ4STl8j62KeiApns4FndA','Députée Obono','person',true,1,true),
('UCSwPcnzaMTuDcTgjRiJvZnw','PCF - Parti communiste français (PCF)','party',true,1,true),
('UCKHKSD-yanY2ZwwU_4Tgf0w','La France insoumise','party',true,1,true),
('UC3lacWBPVK-JfmGyyHx4AAw','OMERTA','media',true,2,true),
('UCfA5DnCDX3Ixy5QOAMGtBlA','Nicolas Dupont-Aignan','person',true,1,true),
('UCB8Q3N-nvX1YlMUL7Zl_16w','Les Écologistes','party',true,1,true),
('UCYpRDnhk5H8h16jpS84uqsA','Le Monde','media',true,2,true),
('UCT67YOMntJxfRnO_9bXDpvw','Le Média','media',true,2,true),
('UC1ObaaFz4XHVPN2T5IFsU4w','Le Nouvel Obs','media',true,2,true),
('UCbXWhsd805LfcbAy7xL9d-A','Le Crayon','media',true,2,true),
('UC3Ma4tRFxx85oZI_XKVTPwg','les Républicains','party',true,1,true),
('UCSKdvgqdnj72_SLggp7BDTg','Brut','media',true,2,true),
('UCm-ftC1IP5k_YwxwyEmWiBA','La Dépêche du Midi','media',true,2,true),
('UCxSUslP_JMH3Bb50oXd1Nnw','Puissance Télévision','media',true,2,true),
('UCA8JG3JY883RjCmAU9lABzw','Sandrine Rousseau','person',true,1,true),
('UCtJk8WNzhAu37r-QBmY7pRA','La Croix','media',true,2,true),
('UC7PX-myPpcT4YfZEWqZxGGg','Sud Ouest','media',true,2,true),
('UCPzRiKcU-bvBMZ08OepxU4w','Radio Classique','media',true,1,true),
('UC2i-BljAg1w_MMMA1JuFm7w','La Provence','media',true,2,true),
('UClaa_CwoQEmSo9Mb_M1f91g','FLORIAN PHILIPPOT','person',true,1,true),
('UCGvjUWz3mGV9cssraATuEsw','Radio Nova','media',true,2,true),
('UC6bn_ABjeTwbJFGFMQbZFlw','Loopsider','media',true,2,true),
('UCo7xGEOV-RfxOAxRfhlR3Ww','PS - Parti socialiste','party',true,1,true),
('UCm4fSpMpPIZ9z6KHoezLUAg','RFI','media',true,2,true),
('UCTItQw_aTIIt1i8ysgYMH3w','Ministère de l''Europe et des Affaires étrangères','institution',true,2,true),
('UC9GGzAhhvhJO1hL10-BcgNA','LeHuffPost','media',true,2,true),
('UCTFjmvpWb_gfIAFsEZqD3NQ','Politicon','media',true,2,true),
('UC0Y9vEv67BYRhgbRwJGj35w','Ministère des Armées et des Anciens combattants','institution',true,2,true),
('UCUsBMOIUl_ad6JUOC16DpmQ','BFM Business','media',true,1,true),
('UCA5aTt71DXLuX78SF2Hcxxw','Edwige Diaz','person',true,1,true),
('UC_KyKHzQdFQo9K1QFa2IyJw','Les Répliques','media',true,2,true),
('UChZWs6PJY0hND384d2_RrhQ','Les Echos','media',true,2,true),
('UC2XZY-bjIEmyLZ9MPJQytZg','David Lisnard','person',true,1,true),
('UC__xRB5L4toU9yYawt_lIKg','BLAST, Le souffle de l''info','media',true,2,true),
('UC3q3FLPQtuWWv1uTkTfpEtw','Antoine Léaument','person',true,1,true),
('UC86dbj-lbDks_hZ5gRKL49Q','AFP News Agency','media',true,2,true),
('UCazDBRKv_Bh6Gf0ebKbFRPQ','France 3 Pays de la Loire','media',true,2,true),
('UCxPd2eZWiZ_ZJax71fyfrnA','Radio J','media',true,1,true),
('UC8-FN_ftL-crIaXMouuykyQ','Au Poste','media',true,2,true),
('UCUzk9hBisz4aSMVTl37pWgw','Lutte ouvrière','party',true,1,true),
('UCl3n298ddvMpS4hkzxE5Cjw','Parlement européen en France','institution',true,2,true),
('UCnflyRN1KOXDp6VM-_EZJgw','Assemblée nationale','institution',true,1,true),
('UCilxiEGEQHVZ25GU_cnyCzg','Mathilde Panot','person',true,1,true),
('UC6V-tTuTNwnnysyYkiHkZ2Q','Radio Notre Dame','media',true,2,true),
('UC4A3K4CT4swDAW57fzXIMVA','Eric Coquerel','person',true,1,true),
('UCeWMp4Frgyv275gSnWNYoZQ','Rassemblement National','party',true,1,true),
('UC7vBQ7qT7sFCHwzwTWeoXBg','Le Zapping du COVID','other',true,3,false),
('UCA3dZqGawAvJO6Lexbj8EGg','Le Monde Moderne','media',true,2,true),
('UCn_smTYmROafIdN_Ykomy8w','France 3 Toutes Régions','media',true,2,true),
('UC45NsEyqTGMtOeEM-UvlTuQ','Regards','media',true,2,true),
('UCjo4wCbga9X01yGwm0gB0Wg','Laurent Wauquiez','person',true,1,true),
('UCI-8QMy9n3I5Pv6mTmXoAXA','Gaspard G','media',true,2,true),
('UCmbhrKMU_X7Gi47bZEEajEQ','StreetPress','media',true,2,true),
('UC4V5osIDMjFwtCRxMm2e0LA','Marianne','media',true,2,true),
('UC9x4Iyu-D257P0P-VDRwSzw','Libération','media',true,2,true),
('UCfsTAnYne5szhoMc381A5wg','L''Opinion','media',true,2,true),
('UCyX-_BipdNpdFgeZEQBNstA','Manon Aubry','person',true,1,true),
('UCr_Oz6MFGScoquaZDKdjD-A','le stUDIo','media',true,2,true),
('UCihYCHXhm3X3qgk0L-hBZxw','Revue Conflits','media',true,2,true),
('UCPaeEhnVIdn4T01gUphIltw','Élysée','institution',true,1,true),
('UCx-1PndeXmfkI8w9MtFQbmA','Thomas Ménagé','person',true,1,true),
('UCLGw2aLOaIa-1XF4IBfFyvg','Léon Deffontaines','person',true,1,true),
('UCEqwfpB34mhHaAx-WE1Tqlg','Bastien Lachaud','person',true,1,true),
('UCv98oI0HCY7ClMpzbTjPznQ','Thomas Portes','person',true,1,true),
('UCFVKtK2LxUkuudXpOGOiUjg','Hadrien Clouet','person',true,1,true),
('UCTyqSSRd75F2suFFgLtFuMg','Ludovic Mendes','person',true,1,true),
('UCKa1uttXqCvGpOyUDfc2wdg','Yan Chantrel','person',true,1,true),
('UCRnWO39xk6YWdbRhdzZ3yXA','Olivier Paccaud','person',true,1,true),
('UCOxXS5E2bR-e_zIgHfvggXA','Jean SOL, Sénateur des Pyrénées-Orientales','person',true,1,true),
('UCcvK-yrz2_dSJUSNDJfq7JA','Anne Hidalgo','person',true,1,true),
('UCXAKlEXGwoavQuOMaNBeaXw','Valérie Pécresse','person',true,1,true),
('UCyVYj4HdtEbcMngyD6_OLzg','Raphaël Glucksmann','person',true,1,true),
('UCcu6jHeGFnTdSfVXr3rh9tA','Aurélien Pradié','person',true,1,true),
('UCdbzUS1IjDZXBxerJL5U_vA','Julien Odoul','person',true,1,true),
('UCDmff0YxGkS8JRMGzaAe-jg','Aurélien Saintoul - Député des Hauts-de-Seine','person',true,1,true),
('UCmYK9AZch3EV33vIFld1QTg','Sébastien Delogu','person',true,1,true),
('UCZgJ_r_Ewlu1Ck-RzNCHuUQ','Clémentine Autain','person',true,1,true),
('UCcru_TwWwshPbjIWvp6B7dg','Louis Boyard','person',true,1,true),
('UCwupzUX-SYyt3y4yx8cYdpg','Marion Maréchal','person',true,1,true),
('UCFmUAFg2tFaRSttT4vMpBNg','Bruno Le Maire','person',true,1,true),
('UCAkBdKn0B-xUlr6TLPx14wg','Gérald DARMANIN','person',true,1,true),
('UCYkZbyXcVmtdRUpCBi713vw','Pure Politique','media',true,2,true),
('UCD2T6hSuOzkT2CMt4iwxw-A','Laurent Mazaury','person',true,1,true),
('UCgv8ahGLkTVp4WyFK2-fymg','Olivier SERVA','person',true,1,true),
('UCPyfEEhMVlNo_waWwkSGCZg','Bertrand Pancher','person',true,1,true),
('UClPZVAobhtv4n1bIPLuLnTg','Guillaume Gontard','person',true,1,true),
('UCoMCFzv2L1q2-xJCvxrB9hg','Rémi Cardon - Sénateur de la Somme','person',true,1,true),
('UCyhzJw7pS5Ks4-hgWfQpU1A','Les secrets de l''Assemblée Nationale','media',true,2,true),
('UCe27I-_81PEpsG_GlYPEBog','Les députés communistes','party',true,1,true),
('UCqQto5vnoiVq3kfX758Lk4g','Députés Renaissance','party',true,1,true),
('UCGHxWumHADmpJEnGZEYRw7A','The Generations','other',true,3,false),
('UCAKzgWr5laB3Yf44hvqqZZQ','NPA - L’Anticapitaliste','party',true,1,true),
('UCixe3VYdKvKavOyopBxsKCw','Place publique','party',true,1,true),
('UC8ba7bn2fuU_lsVweb4YM4Q','Sarah Knafo','person',true,1,true),
('UCjtwBBNjlyd-wPmEFvgbK4w','Union nationale','party',true,1,true),
('UCjTbZBXEw-gplUAnMXLYHpg','Éric Zemmour','person',true,1,true),
('UCJw8np695wqWOaKVhFjkRyg','Renaissance','party',true,1,true),
('UCqaZpAnjhuNJMjk4f68QJSw','Putsch Media','media',true,2,true),
('UCum5JuxrF9qc43AvmZnE_lw','Fréquence Protestante','other',true,3,false),
('UCQKmfKnJ9ZpNLGxjt0RiMJA','Mouv''','media',true,2,true),
('UCR_C4rru48vq0j4zNCujPfw','Beur FM','media',true,2,true),
('UCDn6zvBZNEWUv44xjgELicA','Reporterre 🌍| le média de l''écologie','media',true,2,true),
('UCtjc5x0RIiTsdYS4IFMjCGQ','Politis','media',true,2,true),
('UCLSoWZjCGrdZo7ltIR3lEHg','Causeur','media',true,2,true),
('UC31ilW5A2Y0_V293Ea1ExjQ','Brief.me','media',true,2,true),
('UCGpO8nWNyNeSQjbNlSyro_A','Fondapol','institution',true,2,true),
('UCPgwe5A4feZq2nYBhaQsFDw','IRSEM','institution',true,2,true),
('UCCCf90jjhSxgkR6_Fb-u30g','IRIS','institution',true,2,true),
('UCpfLNjG97sWjGSKYiveWz3w','Institut français des relations internationales','institution',true,2,true),
('UCBSroHXoLzRXEw_6oubTKwg','institutmontaigne','institution',true,2,true),
('UCfNDF4xXMl5L2r5GO_IdgqQ','Fondation Jean-Jaurès','institution',true,2,true),
('UCi1h68Fys0apnhLaJ-ijQOw','INA Politique','media',true,2,true),
('UCmHw3H5Eq05tksL0Df-XP_A','La Voix du Nord','media',true,2,true),
('UCp2kK3DyhpgFOdILF3BBC9A','L''Express','media',true,2,true),
('UCFxDBEN7N1QdECRddUvPivQ','Mardis Grand Continent','other',true,3,false),
('UCXHWT_QoQSsdGXbqF0hAMtg','Arrêt sur images','media',true,2,true),
('UCfidGlehytwCvV3qlsX5uVQ','Front Populaire','party',true,1,true),
('UCQgWpmt02UtJkyO32HGUASQ','Thinkerview','media',true,2,true),
('UCgPYsPyGhhQJQ9zOUQDWDMA','i24NEWS Français','media',true,2,true),
('UCW2QcKZiU8aUGg4yxCIditg','euronews (en français)','media',true,2,true),
('UCG2qip7ARa-yWQ5xmPpPBUQ','Commission européenne en France','institution',true,2,true),
('UCFnbJ89yt8KDIRDDJENRRww','Défenseur des droits','institution',true,2,true),
('UCu4nws5yvkvbcFUjDEh3cgw','Conseil économique social et environnemental','institution',true,2,true),
('UC07oLgmZcMS5JLIW9o9sM4Q','Conseil d''État','institution',true,2,true),
('UCYSL3vTNPcnTMBOKTi1oPBQ','Cour des comptes','institution',true,2,true),
('UCS1lRt6He-GQGhV7W6VeD8w','Ministère de l''Économie et des Finances','institution',true,2,true),
('UCvJ7MfsC_VxHQeYHAIo6Y6A','Ministère de l''Intérieur','institution',true,2,true),
('UCfQpT8ebZlk8PndKVNTiAvA','Gouvernement','institution',true,1,true),
('UCdUat4f2yol7iMpCYoFUmNg','Jean Lassalle','person',true,1,true),
('UCU3z3px1_RCqYBwrs8LJVWg','Marine Le Pen','person',true,1,true),
('UC_2Xe0tzVXvLMvCxmtDmdQA','Manuel Valls','person',true,1,true),
('UCw3waV6T2mhLC3BG8q0W55w','Rachida Dati','person',true,1,true),
('UCFqGa9uitcB-fWyNZK2xImw','Emmanuel Macron','person',true,1,true),
('UCfHn_8-ehdem86fEvlFg-Gw','Le Parisien','media',true,1,true),
('UCOACoqMR83_oB1O3X0xlJzw','Virtual Drug Design Simulations','other',true,3,false),
('UCK5wDULXMDasfob_yHPI2rQ','Sénat','institution',true,1,true),
('UCXKJrYczY2_fJEZgFPGY0HQ','CNEWS','media',true,1,true),
('UCHGFbA0KWBgf6gMbyUCZeCQ','LCP - Assemblée nationale','media',true,1,true),
('UCdL89Z0gQUDc1HT1882AGLw','Aurélien FAGIOLI | IA Automatisation','other',true,3,false),
('UCXwDLMDV86ldKoFVc_g8P0g','BFMTV','media',true,1,true),
('UCESTwDXpoMgiYBHipMdKTkQ','Sud Radio','media',true,1,true),
('UCIMGfEAERXjmWwQeg15BFsg','Europe 1','media',true,1,true),
('UCYsGHGGnGqiyvKESOYIouhQ','Angle Droit','media',true,2,true),
('UCO6K_kkdP-lnSCiO3tPx7WA','franceinfo','media',true,1,true),
('UCysox6U9HnqgCiJ-Pd-Jy_w','Frontières','media',true,2,true),
('UCpi-4daExRSchtsJzO06rwA','Quotidien','media',true,1,true),
('UCrpsdF7UreiF-2r5Jp0YpRg','Ouest-France','media',true,2,true),
('UCJldRgT_D7Am-ErRHQZ90uw','France Inter','media',true,1,true),
('UCIA3flGw7EPkw9c7S-qGjbQ','Ligne Droite • La matinale de Radio Courtoisie','media',true,2,true),
('UCFC3nJ8GXl5yONe3tB_vhsw','France 3 Hauts-de-France','media',true,2,true),
('UCyamXi0qEQJghCjJbj__aWQ','Chaîne officielle TVL','other',true,3,false),
('UCOcDPuYTuxoRBtfmTBXtqBA','Gabriel Attal','person',true,1,true),
('UC3U0VIDgANFaXeOAtt1m5Mw','Jordan Bardella','person',true,1,true),
('UCfHWZNJQ7wZpG_cL9ukYX1Q','MoDem','party',true,1,true),
('UCsrPUA0ZSDCNZC6wyRlR7ZA','TF1 INFO','media',true,1,true),
('UCewhc0fvja891XkpIPGRMxQ','LCI','media',true,1,true),
('UCoDttl6w1T-Stuw_pvNOvLA','Horizons','party',true,1,true),
('UCeu3BbDWzS-XC842DKvmBZA','Dauphine Discussion Débat','other',true,3,false),
('UC5WjQI_NY-PODOQ3kTewebA','ici','media',true,2,true),
('UCyHieXWJ4oewUR3ZTHdyzDw','Eric Ciotti','person',true,1,true),
('UCNlu6bn_Vu37IDINEpVlEog','David Guiraud','person',true,1,true),
('UCDErKauugfWOLRmU16WN5pw','Michaël Delafosse','person',true,1,true),
('UCL2yCOZoelQCQ4iPH75mCNA','Eric Piolle','person',true,1,true),
('UCx8mQU1dOemRUTPmrjs_Jaw','Eric Legaud','person',true,1,true),
('UC9SVhrnsGxWwiBRWT9c7Ozw','RoomieOfficial','other',true,3,false),
('UCCBR4hxc0hMbWs0IfBljQMg','France Télévisions','media',true,2,true),
('UCTa1bPArjpvNMgSHAb_pflA','Public Sénat','media',true,1,true)
on conflict (youtube_channel_id) do nothing;
insert into discovery.channels (youtube_channel_id, title, kind, in_daily_subscriptions, priority, active)
select youtube_channel_id, youtube_channel_title, 'person', false, 1, true from discovery.persons
 where youtube_channel_id like 'UC%' on conflict (youtube_channel_id) do nothing;
-- lien chaîne perso -> personne
update discovery.channels c set person_id = p.id from discovery.persons p where p.youtube_channel_id = c.youtube_channel_id and c.person_id is null;
-- chaînes déjà connues de la pipeline Loïc
insert into discovery.channels (youtube_channel_id, title, kind, in_daily_subscriptions, public_channel_id, priority, active)
select y.youtube_id, y.title, 'media', false, y.id, 2, y.active from public.youtube_channels y
 where y.youtube_id is not null on conflict (youtube_channel_id) do update set public_channel_id = excluded.public_channel_id;
select kind, count(*) n, count(*) filter (where in_daily_subscriptions) suivies, count(public_channel_id) chez_loic from discovery.channels group by kind order by kind;