insert into discovery.persons (display_name, aliases, party, role, tier, status_2027, youtube_channel_id, youtube_channel_title) values
('Marine Le Pen',ARRAY['Marine Le Pen','M. Le Pen','Le Pen']::text[],'Rassemblement national','présidente du groupe RN à l''Assemblée',1,'declare','UCU3z3px1_RCqYBwrs8LJVWg','Marine Le Pen'),
('Jordan Bardella',ARRAY['Bardella']::text[],'Rassemblement national','président du RN',1,'pressenti','UC3U0VIDgANFaXeOAtt1m5Mw','Jordan Bardella'),
('Gabriel Attal',ARRAY['Attal']::text[],'Renaissance','président de Renaissance, ancien Premier ministre',1,'declare','UCOcDPuYTuxoRBtfmTBXtqBA','Gabriel Attal'),
('Édouard Philippe',ARRAY['Édouard Philippe','Edouard Philippe','E. Philippe']::text[],'Horizons','maire du Havre, ancien Premier ministre',1,'declare',NULL,'@AvecEdouard'),
('Bruno Retailleau',ARRAY['Retailleau']::text[],'Les Républicains','président de LR, ancien ministre de l''Intérieur',1,'declare',NULL,'@Bruno_Retailleau'),
('Jean-Luc Mélenchon',ARRAY['Mélenchon','Melenchon','JLM']::text[],'La France insoumise','fondateur de LFI',1,'declare','UCk-_PEY3iC6DIGJKuoEe9bw','JEAN-LUC MÉLENCHON'),
('Marine Tondelier',ARRAY['Tondelier']::text[],'Les Écologistes','secrétaire nationale des Écologistes',1,'declare',NULL,NULL),
('Fabien Roussel',ARRAY['Fabien Roussel','F. Roussel']::text[],'Parti communiste français','secrétaire national du PCF',1,'declare','UCHQbUAkpnkf_Yg6-xAqj-ZA','UCHQbUAkpnkf_Yg6-xAqj-ZA'),
('Raphaël Glucksmann',ARRAY['Glucksmann']::text[],'Place publique','député européen',1,'pressenti','UCyVYj4HdtEbcMngyD6_OLzg','Raphaël Glucksmann'),
('Éric Zemmour',ARRAY['Zemmour']::text[],'Reconquête','président de Reconquête',1,'pressenti','UCjTbZBXEw-gplUAnMXLYHpg','Éric Zemmour'),
('Dominique de Villepin',ARRAY['Villepin']::text[],'La France humaniste','ancien Premier ministre',1,'pressenti',NULL,'@dominiquedevillepin'),
('François Hollande',ARRAY['Hollande']::text[],'Parti socialiste','ancien président de la République, député',1,'pressenti',NULL,NULL),
('Xavier Bertrand',ARRAY['Xavier Bertrand','X. Bertrand']::text[],'Les Républicains','président de la région Hauts-de-France',1,'pressenti',NULL,'@xavierbertrand02'),
('Karim Bouamrane',ARRAY['Bouamrane']::text[],'Parti socialiste','maire de Saint-Ouen-sur-Seine',1,'declare',NULL,NULL),
('Olivier Faure',ARRAY['Olivier Faure','O. Faure']::text[],'Parti socialiste','premier secrétaire du PS',1,'pressenti',NULL,NULL),
('Nicolas Dupont-Aignan',ARRAY['Dupont-Aignan','NDA']::text[],'Debout la France','président de DLF',1,'declare','UCfA5DnCDX3Ixy5QOAMGtBlA','Nicolas Dupont-Aignan'),
('Florian Philippot',ARRAY['Philippot']::text[],'Les Patriotes','président des Patriotes',1,'declare','UClaa_CwoQEmSo9Mb_M1f91g','FLORIAN PHILIPPOT'),
('François Asselineau',ARRAY['Asselineau']::text[],'Union populaire républicaine','président de l''UPR',1,'declare',NULL,'@f_asselineau'),
('Nathalie Arthaud',ARRAY['Arthaud']::text[],'Lutte ouvrière','porte-parole de LO',1,'declare',NULL,NULL),
('Gérald Darmanin',ARRAY['Darmanin']::text[],'Renaissance','garde des Sceaux',1,'pressenti','UCAkBdKn0B-xUlr6TLPx14wg','Gérald DARMANIN'),
('François Ruffin',ARRAY['Ruffin']::text[],'Debout !','député de la Somme',1,'pressenti','UCIQGSp79vVch0vO3Efqif_w','FRANÇOIS RUFFIN'),
('Bernard Cazeneuve',ARRAY['Bernard Cazeneuve','B. Cazeneuve']::text[],'La Convention','ancien Premier ministre',1,'pressenti',NULL,NULL),
('Emmanuel Macron',ARRAY['Macron']::text[],'Renaissance','président de la République',1,'non_candidat','UCFqGa9uitcB-fWyNZK2xImw','Emmanuel Macron'),
('Sébastien Lecornu',ARRAY['Lecornu']::text[],'Renaissance','Premier ministre',1,'non_candidat',NULL,NULL),
('François Bayrou',ARRAY['Bayrou']::text[],'Mouvement démocrate','ancien Premier ministre, président du MoDem',1,'pressenti',NULL,'@FrancoisBayrou-FBDirect'),
('Laurent Wauquiez',ARRAY['Wauquiez']::text[],'Les Républicains','président du groupe DR à l''Assemblée',2,NULL,'UCjo4wCbga9X01yGwm0gB0Wg','Laurent Wauquiez'),
('Marion Maréchal',ARRAY['Marion Maréchal','Maréchal']::text[],'Identité-Libertés','députée européenne',2,NULL,'UCwupzUX-SYyt3y4yx8cYdpg','Marion Maréchal'),
('Sarah Knafo',ARRAY['Knafo']::text[],'Reconquête','députée européenne',2,NULL,'UC8ba7bn2fuU_lsVweb4YM4Q','Sarah Knafo'),
('Manuel Bompard',ARRAY['Bompard']::text[],'La France insoumise','coordinateur de LFI',2,NULL,NULL,'@manuelbompard'),
('Mathilde Panot',ARRAY['Panot']::text[],'La France insoumise','présidente du groupe LFI à l''Assemblée',2,NULL,'UCilxiEGEQHVZ25GU_cnyCzg','Mathilde Panot'),
('Clémentine Autain',ARRAY['Autain']::text[],'L''Après','députée',2,NULL,'UCZgJ_r_Ewlu1Ck-RzNCHuUQ','Clémentine Autain'),
('Éric Ciotti',ARRAY['Ciotti']::text[],'Union des droites pour la République','président de l''UDR',2,NULL,'UCyHieXWJ4oewUR3ZTHdyzDw','Eric Ciotti'),
('Sandrine Rousseau',ARRAY['Sandrine Rousseau']::text[],'Les Écologistes','députée',2,NULL,'UCA8JG3JY883RjCmAU9lABzw','Sandrine Rousseau'),
('Valérie Pécresse',ARRAY['Pécresse','Pecresse']::text[],'Les Républicains','présidente de la région Île-de-France',2,NULL,'UCXAKlEXGwoavQuOMaNBeaXw','Valérie Pécresse'),
('Manon Aubry',ARRAY['Manon Aubry']::text[],'La France insoumise','députée européenne',2,NULL,'UCyX-_BipdNpdFgeZEQBNstA','Manon Aubry'),
('Rima Hassan',ARRAY['Rima Hassan']::text[],'La France insoumise','députée européenne',2,NULL,NULL,NULL),
('Louis Boyard',ARRAY['Boyard']::text[],'La France insoumise','député',2,NULL,'UCcru_TwWwshPbjIWvp6B7dg','Louis Boyard'),
('Léon Deffontaines',ARRAY['Deffontaines']::text[],'Parti communiste français','porte-parole du PCF',2,NULL,'UCLGw2aLOaIa-1XF4IBfFyvg','Léon Deffontaines'),
('Delphine Batho',ARRAY['Batho']::text[],'Génération écologie','députée',2,'declare',NULL,NULL),
('Boris Vallaud',ARRAY['Boris Vallaud']::text[],'Parti socialiste','président du groupe PS à l''Assemblée',2,NULL,NULL,NULL),
('Carole Delga',ARRAY['Delga']::text[],'Parti socialiste','présidente de la région Occitanie',2,NULL,NULL,NULL),
('Yannick Jadot',ARRAY['Jadot']::text[],'Les Écologistes','sénateur',2,NULL,NULL,NULL),
('David Lisnard',ARRAY['Lisnard']::text[],'Nouvelle Énergie','maire de Cannes',2,NULL,'UC2XZY-bjIEmyLZ9MPJQytZg','David Lisnard'),
('Yaël Braun-Pivet',ARRAY['Braun-Pivet']::text[],'Renaissance','présidente de l''Assemblée nationale',2,NULL,NULL,NULL),
('Gérard Larcher',ARRAY['Larcher']::text[],'Les Républicains','président du Sénat',2,NULL,NULL,NULL),
('Élisabeth Borne',ARRAY['Borne']::text[],'Renaissance','ancienne Première ministre',2,NULL,NULL,NULL),
('Rachida Dati',ARRAY['Dati']::text[],'Les Républicains','ministre de la Culture',2,NULL,'UCw3waV6T2mhLC3BG8q0W55w','Rachida Dati'),
('Bruno Le Maire',ARRAY['Le Maire']::text[],'Renaissance','ancien ministre de l''Économie',2,NULL,'UCFmUAFg2tFaRSttT4vMpBNg','Bruno Le Maire'),
('Michel Barnier',ARRAY['Barnier']::text[],'Les Républicains','ancien Premier ministre',2,NULL,NULL,NULL),
('Aurore Bergé',ARRAY['Bergé','Berge']::text[],'Renaissance','ministre',2,NULL,NULL,NULL),
('Marie Toussaint',ARRAY['Marie Toussaint']::text[],'Les Écologistes','députée européenne',2,NULL,NULL,NULL),
('Cyrielle Chatelain',ARRAY['Chatelain']::text[],'Les Écologistes','présidente du groupe écologiste à l''Assemblée',2,NULL,NULL,NULL),
('Philippe Poutou',ARRAY['Poutou']::text[],'Nouveau Parti anticapitaliste','porte-parole du NPA',2,NULL,NULL,NULL),
('Jean Lassalle',ARRAY['Lassalle']::text[],'Résistons !','ancien député',2,NULL,'UCdUat4f2yol7iMpCYoFUmNg','Jean Lassalle'),
('Philippe de Villiers',ARRAY['Villiers']::text[],'Mouvement pour la France','ancien président du MPF',2,NULL,NULL,NULL);
update discovery.persons d set person_id = p.id from public.persons p
 where d.person_id is null and lower(p.display_name) = lower(d.display_name);
select count(*) total, count(person_id) linked, count(youtube_channel_id) filter (where youtube_channel_id like 'UC%') with_channel_id from discovery.persons;